complete.cases() returns true if case has no NAs

correlation matrix cor()
correlation plot: cor(df) %>% corplot()

Video: dimensionality reduction techniques
dimensionality ~~ number of variables per observation

PCA
components are uncorrelated to eachother
1st captures most variance, 2nd most of remaining variance etc. -> *Order of importance*
assumes that features(variables) with mre variance are more important -> standardization of data

"There are two functions in the default package distribution of R that can be used to perform PCA: princomp() and prcomp(). The prcomp() function uses the SVD and is the preferred, more numerically accurate method."

standardization of data: scale()

prcomp(df) %>% biplot()

-> scatter plot of observations according to PC1 and PC2
arrows represet the original features 
  -> pointing same way = pos. correlation
    -> 90 deg angle = no correlation
  -> pointing same way as axis: correlated to the PC
  
Multiple correspondence analysis (MCA): like PCA but for categorical variables

```{r}
library(FactoMineR)
data(tea)
# column names to keep in the dataset
keep_columns <- c("Tea", "How", "how", "sugar", "where", "lunch")

# select the 'keep_columns' to create a new dataset
tea_time <- select(tea, one_of(keep_columns))

# multiple correspondence analysis
mca <- MCA(tea_time, graph = FALSE)

# summary of the model
summary(mca)

# visualize MCA
plot(mca, invisible=c("ind"), habillage = "quali")
```


